server:
  port: 9595

eureka:
  instance:
    hostname: localhost   #主机名
  client:
    registerWithEureka: false  # 是否将自己的路径注册到eureka上。单机单机eureka server不需要   eureka provider client 需要
    fetchRegistry: false  # 是否需要从eureka中抓取路径。单机eureka server 不需要的，eureka consumer client 需要
    serviceUrl:
      defaultZone: http://localhost:9595/eureka/  # eureka服务端地址，将来客户端使用该地址和eureka进行通信

spring:
  application:
    name: eureka-demo # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径