server:
  port: 9502

eureka:
  instance:
    hostname: eureka9502.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9501/eureka/,http://localhost:9503/eureka/

spring:
  application:
    name: eureka9502